name: Build

on:
  push:
    branches: ["**"]
    paths:
      - 'Plugin/CustomFloorPlugin/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: ["**"]
    paths:
      - 'Plugin/CustomFloorPlugin/**'
      - '.github/workflows/main.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Actions
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: 6.0.x
      - name: Get Stripped Refs
        env:
          FILES_URL: ${{ secrets.BSFILES_URL }}
        run: wget --no-check-certificate "$FILES_URL" -q -O bsfiles.zip
      - name: Extract Refs
        run: unzip -q -n bsfiles.zip -d ./Plugin/Refs
      - name: Build
        id: Build
        env:
          FrameworkPathOverride: /usr/lib/mono/4.8-api
        run: dotnet build ./Plugin/CustomFloorPlugin.sln --configuration Release
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: ${{ steps.Build.outputs.filename }}
          path: ${{ steps.Build.outputs.artifactpath }}
      - name: Upload Unity Project Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Unity Project
          path: |
            ./Unity/
            !./Unity/Script
